# Generated by Django 4.2.10 on 2026-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_refresh_seconds', models.PositiveIntegerField(default=10, verbose_name='仪表盘刷新秒数')),
                ('demand_warning_threshold', models.PositiveIntegerField(default=15, verbose_name='供需预警阈值')),
                ('prediction_horizon_hours', models.PositiveIntegerField(default=48, verbose_name='预测时长')),
                ('dispatch_trigger_threshold', models.PositiveIntegerField(default=15, verbose_name='调度触发阈值')),
                ('model_version', models.CharField(default='untrained', max_length=64, verbose_name='当前模型版本')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.AlterField(
            model_name='regionfeature',
            name='population_density',
            field=models.FloatField(blank=True, null=True, verbose_name='人口密度'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('upload', '数据上传'), ('predict', '需求预测'), ('schedule', '调度任务'), ('backup', '数据备份'), ('export', '报表导出'), ('error', '错误操作'), ('setting', '系统设置')], max_length=20, verbose_name='操作类型'),
        ),
    ]
