# Generated by Django 4.2.10 on 2026-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_support", "0002_systemsetting_alter_regionfeature_population_density_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "系统管理员"),
                    ("operator", "运维调度员"),
                    ("predictor", "数据分析员"),
                ],
                default="predictor",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
    ]
