# Generated by Django 4.2.10 on 2026-01-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.CharField(max_length=30, unique=True, verbose_name='单车编号')),
                ('status', models.CharField(choices=[('normal', '正常'), ('fault', '故障'), ('maintain', '维护中')], max_length=20, verbose_name='车辆状态')),
                ('current_region', models.CharField(choices=[('region1', '区域1'), ('region2', '区域2'), ('region3', '区域3'), ('region4', '区域4')], max_length=20, verbose_name='当前区域')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '运维车辆',
                'verbose_name_plural': '运维车辆',
            },
        ),
    ]
