# Generated by Django 4.2.10 on 2026-03-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('track_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='位置描述')),
            ],
            options={
                'verbose_name': '运维轨迹',
                'verbose_name_plural': '运维轨迹',
                'ordering': ['-track_time'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('parking_spot_id', models.AutoField(primary_key=True, serialize=False, verbose_name='停车点ID')),
                ('spot_name', models.CharField(max_length=100, unique=True, verbose_name='停车点名称')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('campus_area', models.CharField(choices=[('西校区', '西校区'), ('东校区', '东校区')], default='西校区', max_length=20, verbose_name='所属校区')),
                ('spot_type', models.CharField(choices=[('教学楼', '教学楼'), ('食堂', '食堂'), ('场馆', '场馆'), ('其他', '其他')], default='其他', max_length=20, verbose_name='停车点类型')),
                ('service_radius', models.IntegerField(default=100, verbose_name='服务半径(米)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '停车点',
                'verbose_name_plural': '停车点',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_rate', models.FloatField(verbose_name='完成率(%)')),
                ('time_efficiency', models.FloatField(verbose_name='时间效率(分钟)')),
                ('cost_efficiency', models.FloatField(blank=True, null=True, verbose_name='成本效率')),
                ('satisfaction_score', models.FloatField(blank=True, null=True, verbose_name='满意度评分')),
                ('evaluation_time', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
                ('notes', models.TextField(blank=True, verbose_name='评估备注')),
            ],
            options={
                'verbose_name': '调度效果评估',
                'verbose_name_plural': '调度效果评估',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务编号')),
                ('task_type', models.CharField(default='vehicle_dispatch', max_length=50, verbose_name='任务类型')),
                ('start_location', models.CharField(max_length=100, verbose_name='起始位置')),
                ('end_location', models.CharField(max_length=100, verbose_name='目标位置')),
                ('dispatch_count', models.IntegerField(default=0, verbose_name='调度数量')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('predicted_time', models.DateTimeField(blank=True, null=True, verbose_name='预测时间')),
            ],
            options={
                'verbose_name': '调度任务',
                'verbose_name_plural': '调度任务',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='车辆编号')),
                ('status', models.CharField(choices=[('available', '可用'), ('ridden', '已骑行'), ('faulty', '故障'), ('locked', '锁定')], default='available', max_length=20, verbose_name='车辆状态')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation_management.parkingspot', verbose_name='所属停车点')),
            ],
            options={
                'verbose_name': '运维车辆',
                'verbose_name_plural': '运维车辆',
                'ordering': ['-update_time'],
            },
        ),
    ]
