# Generated by Django 4.2.10 on 2026-01-29 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand_prediction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-update_time'], 'verbose_name': '运维车辆', 'verbose_name_plural': '运维车辆'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('fault', '故障'), ('maintain', '维护中'), ('offline', '离线')], default='normal', max_length=20, verbose_name='车辆状态'),
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('target_region', models.CharField(choices=[('region1', '区域1'), ('region2', '区域2'), ('region3', '区域3'), ('region4', '区域4')], max_length=20, verbose_name='目标区域')),
                ('source_region', models.CharField(blank=True, choices=[('region1', '区域1'), ('region2', '区域2'), ('region3', '区域3'), ('region4', '区域4')], max_length=20, null=True, verbose_name='源区域')),
                ('demand_count', models.IntegerField(verbose_name='需求车辆数')),
                ('actual_count', models.IntegerField(default=0, verbose_name='实际调度数')),
                ('status', models.CharField(choices=[('pending', '待分配'), ('assigned', '已分配'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='分配给')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('prediction_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand_prediction.predictionresult', verbose_name='关联预测结果')),
            ],
            options={
                'verbose_name': '调度任务',
                'verbose_name_plural': '调度任务',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_rate', models.FloatField(verbose_name='完成率(%)')),
                ('time_efficiency', models.FloatField(verbose_name='时间效率(分钟)')),
                ('cost_efficiency', models.FloatField(blank=True, null=True, verbose_name='成本效率')),
                ('satisfaction_score', models.FloatField(blank=True, null=True, verbose_name='满意度评分')),
                ('evaluation_time', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
                ('notes', models.TextField(blank=True, verbose_name='评估备注')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评估人')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operation_management.scheduletask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '调度效果评估',
                'verbose_name_plural': '调度效果评估',
            },
        ),
        migrations.CreateModel(
            name='OperatorTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('track_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='位置描述')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL, verbose_name='运维人员')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='operation_management.scheduletask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '运维轨迹',
                'verbose_name_plural': '运维轨迹',
                'ordering': ['-track_time'],
            },
        ),
    ]
