# Generated by Django 4.2.10 on 2026-03-11 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevaluation',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评估人'),
        ),
        migrations.AddField(
            model_name='scheduleevaluation',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operation_management.scheduletask', verbose_name='关联任务'),
        ),
        migrations.AddField(
            model_name='operatortrack',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL, verbose_name='运维人员'),
        ),
        migrations.AddField(
            model_name='operatortrack',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='operation_management.scheduletask', verbose_name='关联任务'),
        ),
    ]
