# Generated by Django 4.2.10 on 2026-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_management', '0002_alter_vehicle_options_vehicle_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='停车点编号')),
                ('name', models.CharField(max_length=100, verbose_name='停车点名称')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('service_radius', models.IntegerField(default=100, verbose_name='服务半径(米)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '停车点',
                'verbose_name_plural': '停车点',
            },
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='actual_count',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='demand_count',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='prediction_result',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='source_region',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='target_region',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_region',
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='dispatch_count',
            field=models.IntegerField(default=0, verbose_name='调度数量'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='end_location',
            field=models.CharField(default='', max_length=100, verbose_name='目标位置'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='predicted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预测时间'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='start_location',
            field=models.CharField(default='', max_length=100, verbose_name='起始位置'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='task_type',
            field=models.CharField(default='vehicle_dispatch', max_length=50, verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='parking_spot_id',
            field=models.CharField(default=0, max_length=30, verbose_name='所属停车点ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='车辆编号'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='纬度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='经度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('ridden', '已骑行'), ('faulty', '故障'), ('locked', '锁定')], default='available', max_length=20, verbose_name='车辆状态'),
        ),
    ]
