# Generated by Django 4.2.10 on 2026-04-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ['ysu_id'], 'verbose_name': '站点主数据', 'verbose_name_plural': '站点主数据'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['id'], 'verbose_name': '运维车辆', 'verbose_name_plural': '运维车辆'},
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='high_warning_threshold',
            field=models.PositiveIntegerField(default=32, verbose_name='高饱和预警阈值'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='initial_inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='初始车辆投放数'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='low_warning_threshold',
            field=models.PositiveIntegerField(default=8, verbose_name='低存量预警阈值'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=40, verbose_name='最大承载容量'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='notes',
            field=models.TextField(blank=True, verbose_name='运维备注'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='washington_station_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='华盛顿映射站点ID'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='washington_station_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='华盛顿映射站点名称'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='ysu_id',
            field=models.IntegerField(default=1, verbose_name='站点编号'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='distance_cost',
            field=models.FloatField(default=0, verbose_name='调度距离成本'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='from_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_source_tasks', to='operation_management.parkingspot', verbose_name='调出站点'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='predicted_gap',
            field=models.FloatField(default=0, verbose_name='触发时预测缺口'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='prediction_batch_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预测批次时间'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='reason',
            field=models.TextField(blank=True, verbose_name='调度原因'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_target_tasks', to='operation_management.parkingspot', verbose_name='调入站点'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='campus_area',
            field=models.CharField(choices=[('west', '西校区'), ('east', '东校区'), ('mixed', '跨区')], default='mixed', max_length=20, verbose_name='所属校区'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='parking_spot_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='站点主键'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='站点名称'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('academic', '教学科研'), ('residential', '生活居住'), ('comprehensive', '综合服务'), ('transit', '交通枢纽')], default='academic', max_length=20, verbose_name='站点类型'),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='predicted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预测时刻'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='parking_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation_management.parkingspot', verbose_name='所属站点'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('ridden', '骑行中'), ('faulty', '故障'), ('locked', '锁定'), ('in_transit', '调度在途')], default='available', max_length=20, verbose_name='车辆状态'),
        ),
    ]
