# Generated by Django 4.2.10 on 2026-04-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_management', '0003_alter_parkingspot_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='related_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_tasks', to='operation_management.vehicle', verbose_name='关联车辆'),
        ),
        migrations.CreateModel(
            name='VehicleLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='变更前状态')),
                ('current_status', models.CharField(blank=True, max_length=20, verbose_name='变更后状态')),
                ('change_reason', models.CharField(blank=True, max_length=200, verbose_name='变更原因')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_history_to', to='operation_management.parkingspot', verbose_name='当前站点')),
                ('previous_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_history_from', to='operation_management.parkingspot', verbose_name='前一站点')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_histories', to='operation_management.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '车辆位置轨迹',
                'verbose_name_plural': '车辆位置轨迹',
                'ordering': ['-changed_at'],
            },
        ),
    ]
