# Generated by Cursor on 2026-06-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_support", "0003_alter_user_role"),
        ("operation_management", "0004_scheduletask_related_vehicle_vehiclelocationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduletask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_schedule_tasks",
                to="system_support.user",
                verbose_name="工单发起人",
            ),
        ),
        migrations.AddField(
            model_name="scheduletask",
            name="creator_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "系统管理员"),
                    ("predictor", "数据分析员"),
                    ("operator", "运维调度员"),
                ],
                max_length=20,
                verbose_name="发起人角色",
            ),
        ),
    ]
