# Generated by Django 4.2.10 on 2026-01-19 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('public', '公开数据集'), ('local', '本地录入')], max_length=20, verbose_name='数据来源')),
                ('start_point', models.CharField(max_length=100, verbose_name='起始区域')),
                ('end_point', models.CharField(max_length=100, verbose_name='结束区域')),
                ('ride_datetime', models.DateTimeField(verbose_name='骑行时间')),
                ('duration', models.FloatField(verbose_name='骑行时长（分钟）')),
                ('distance', models.FloatField(verbose_name='骑行里程（公里）')),
                ('weather', models.CharField(choices=[('sunny', '晴天'), ('rainy', '雨天'), ('cloudy', '阴天')], max_length=20, verbose_name='天气')),
                ('temperature', models.FloatField(verbose_name='温度（℃）')),
                ('wind_speed', models.FloatField(verbose_name='风速（m/s）')),
                ('status', models.CharField(choices=[('uncleaned', '未清洗'), ('cleaned', '已清洗')], default='uncleaned', max_length=20, verbose_name='数据状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '骑行数据',
                'verbose_name_plural': '骑行数据',
                'ordering': ['-ride_datetime'],
            },
        ),
    ]
