# Generated by Django 4.2.10 on 2026-03-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='区域')),
                ('date', models.DateField(verbose_name='日期')),
                ('temperature', models.FloatField(verbose_name='温度(℃)')),
                ('humidity', models.FloatField(verbose_name='湿度(%)')),
                ('wind_speed', models.FloatField(verbose_name='风速(m/s)')),
                ('rainfall', models.FloatField(default=0, verbose_name='降雨量(mm)')),
                ('weather_type', models.CharField(choices=[('sunny', '晴'), ('cloudy', '阴'), ('rain', '雨')], max_length=20, verbose_name='天气类型')),
            ],
            options={
                'verbose_name': '天气数据',
                'verbose_name_plural': '天气数据',
                'unique_together': {('area', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSpotRealTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(verbose_name='数据采集时刻')),
                ('parked_count', models.IntegerField(default=0, verbose_name='当前时刻停放车辆数')),
                ('riding_count', models.IntegerField(default=0, verbose_name='当前时刻骑行中车辆数')),
                ('fault_count', models.IntegerField(default=0, verbose_name='当前时刻故障车辆数')),
                ('demand_count', models.IntegerField(default=0, verbose_name='当前时刻基于用户行为的需求量')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_management.parkingspot', verbose_name='停车点')),
            ],
            options={
                'verbose_name': '实时停车点数据',
                'verbose_name_plural': '实时停车点数据',
                'ordering': ['-collect_time'],
            },
        ),
        migrations.CreateModel(
            name='DataProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_count', models.IntegerField(default=0, verbose_name='真实停车量')),
                ('status', models.CharField(choices=[('normal', '正常'), ('error', '异常')], default='normal', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation_management.parkingspot', verbose_name='停车点')),
            ],
            options={
                'verbose_name': '数据处理日志',
                'verbose_name_plural': '数据处理日志',
            },
        ),
        migrations.CreateModel(
            name='BikeRideData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=50, verbose_name='数据来源')),
                ('start_point', models.CharField(max_length=100, verbose_name='骑行起点')),
                ('end_point', models.CharField(max_length=100, verbose_name='骑行终点')),
                ('ride_datetime', models.DateTimeField(verbose_name='骑行时间')),
                ('duration', models.FloatField(default=0.0, verbose_name='骑行时长')),
                ('distance', models.FloatField(default=0.0, verbose_name='骑行距离')),
                ('temperature', models.FloatField(default=25.0, verbose_name='温度')),
                ('wind_speed', models.FloatField(default=0.0, verbose_name='风速')),
                ('status', models.CharField(default='cleaned', max_length=20, verbose_name='数据状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '骑行数据',
                'verbose_name_plural': '骑行数据',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpotSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='记录时间')),
                ('parked_count', models.IntegerField(default=0, verbose_name='停放车辆数')),
                ('riding_count', models.IntegerField(default=0, verbose_name='骑行中车辆数')),
                ('fault_count', models.IntegerField(default=0, verbose_name='故障车辆数')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_management.parkingspot', verbose_name='停车点')),
            ],
            options={
                'verbose_name': '停车点快照',
                'verbose_name_plural': '停车点快照',
                'ordering': ['-timestamp'],
                'unique_together': {('parking_spot', 'timestamp')},
            },
        ),
    ]
