# Generated by Django 4.2.10 on 2026-03-05 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation_management', '0001_initial'),
        ('data_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspotsnapshot',
            name='parking_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_management.parkingspot', verbose_name='停车点'),
        ),
        migrations.AddField(
            model_name='dataprocesslog',
            name='parking_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation_management.parkingspot', verbose_name='停车点'),
        ),
    ]
