# Generated by Django 4.2.10 on 2026-04-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_management', '0003_alter_parkingspot_options_alter_vehicle_options_and_more'),
        ('data_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspotrealtime',
            options={'ordering': ['-collect_time', 'parking_spot_id'], 'verbose_name': '实时站点状态', 'verbose_name_plural': '实时站点状态'},
        ),
        migrations.AlterModelOptions(
            name='parkingspotsnapshot',
            options={'ordering': ['-timestamp'], 'verbose_name': '站点小时快照', 'verbose_name_plural': '站点小时快照'},
        ),
        migrations.AddField(
            model_name='parkingspotrealtime',
            name='in_transit_count',
            field=models.IntegerField(default=0, verbose_name='当前在途车辆数'),
        ),
        migrations.AlterField(
            model_name='dataprocesslog',
            name='actual_count',
            field=models.IntegerField(default=0, verbose_name='真实停放量'),
        ),
        migrations.AlterField(
            model_name='dataprocesslog',
            name='parking_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation_management.parkingspot', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='parkingspotrealtime',
            name='collect_time',
            field=models.DateTimeField(verbose_name='采集时间'),
        ),
        migrations.AlterField(
            model_name='parkingspotrealtime',
            name='demand_count',
            field=models.IntegerField(default=0, verbose_name='当前需求量'),
        ),
        migrations.AlterField(
            model_name='parkingspotrealtime',
            name='fault_count',
            field=models.IntegerField(default=0, verbose_name='当前故障车辆数'),
        ),
        migrations.AlterField(
            model_name='parkingspotrealtime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkingspotrealtime',
            name='parked_count',
            field=models.IntegerField(default=0, verbose_name='当前停放车辆数'),
        ),
        migrations.AlterField(
            model_name='parkingspotrealtime',
            name='parking_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_management.parkingspot', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='parkingspotrealtime',
            name='riding_count',
            field=models.IntegerField(default=0, verbose_name='当前骑行中车辆数'),
        ),
        migrations.AlterField(
            model_name='parkingspotsnapshot',
            name='parking_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_management.parkingspot', verbose_name='站点'),
        ),
    ]
