# Generated by Django 4.2.10 on 2026-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeridedata',
            name='weather',
        ),
        migrations.AddField(
            model_name='bikeridedata',
            name='temperature',
            field=models.FloatField(default=25.0, verbose_name='温度'),
        ),
        migrations.AddField(
            model_name='bikeridedata',
            name='wind_speed',
            field=models.FloatField(default=0.0, verbose_name='风速'),
        ),
    ]
