# Generated by Django 4.2.10 on 2026-01-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikeridedata',
            options={'verbose_name': '骑行数据', 'verbose_name_plural': '骑行数据'},
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='data_source',
            field=models.CharField(max_length=50, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='distance',
            field=models.FloatField(default=0.0, verbose_name='骑行距离'),
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='duration',
            field=models.FloatField(default=0.0, verbose_name='骑行时长'),
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='end_point',
            field=models.CharField(max_length=100, verbose_name='骑行终点'),
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='start_point',
            field=models.CharField(max_length=100, verbose_name='骑行起点'),
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='status',
            field=models.CharField(default='cleaned', max_length=20, verbose_name='数据状态'),
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='temperature',
            field=models.FloatField(default=25.0, verbose_name='温度'),
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='weather',
            field=models.CharField(default='sunny', max_length=20, verbose_name='天气'),
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='wind_speed',
            field=models.FloatField(default=0.0, verbose_name='风速'),
        ),
    ]
