# Generated by Django 4.2.10 on 2026-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0002_remove_bikeridedata_weather_bikeridedata_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_spot_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='停车点ID')),
                ('parking_spot_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='停车点名称')),
                ('actual_count', models.IntegerField(default=0, verbose_name='真实停车量')),
                ('status', models.CharField(choices=[('normal', '正常'), ('error', '异常')], default='normal', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据处理日志',
                'verbose_name_plural': '数据处理日志',
            },
        ),
    ]
