# Generated by Django 4.2.10 on 2026-01-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0002_alter_bikeridedata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeridedata',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='bikeridedata',
            name='wind_speed',
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='区域')),
                ('date', models.DateField(verbose_name='日期')),
                ('temperature', models.FloatField(verbose_name='温度(℃)')),
                ('humidity', models.FloatField(verbose_name='湿度(%)')),
                ('wind_speed', models.FloatField(verbose_name='风速(m/s)')),
                ('rainfall', models.FloatField(default=0, verbose_name='降雨量(mm)')),
                ('weather_type', models.CharField(choices=[('sunny', '晴'), ('cloudy', '阴'), ('rain', '雨')], max_length=20, verbose_name='天气类型')),
            ],
            options={
                'verbose_name': '天气数据',
                'verbose_name_plural': '天气数据',
                'unique_together': {('area', 'date')},
            },
        ),
        migrations.AlterField(
            model_name='bikeridedata',
            name='weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_process.weatherdata', verbose_name='关联天气数据'),
        ),
    ]
