# Generated by Django 4.2.10 on 2026-03-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_management', '0002_initial'),
        ('data_process', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpotRealTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(verbose_name='数据采集时刻')),
                ('parked_count', models.IntegerField(default=0, verbose_name='当前时刻停放车辆数')),
                ('riding_count', models.IntegerField(default=0, verbose_name='当前时刻骑行中车辆数')),
                ('fault_count', models.IntegerField(default=0, verbose_name='当前时刻故障车辆数')),
                ('demand_count', models.IntegerField(default=0, verbose_name='当前时刻基于用户行为的需求量')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_management.parkingspot', verbose_name='停车点')),
            ],
            options={
                'verbose_name': '实时停车点数据',
                'verbose_name_plural': '实时停车点数据',
                'ordering': ['-collect_time'],
            },
        ),
    ]
